# A docker compose configuration for running "release" builds.
# To be used as `-f docker-compose.yaml -f docker-compose.override.release.yaml`. You must specify this sequence of config files to your `docker compose ...` commands.

services:
  api:
    build:
      context: ../ccn-coverage-api
      target: release-stage
      tags: ['local-connectivity-lab/ccn-coverage-api:release']

  vis:
    build:
      context: ../ccn-coverage-vis
      target: release-stage
      tags: ['local-connectivity-lab/ccn-coverage-vis:release']

  nginx:
    environment:
      CCN_VIS_PORT: 80
